spring:
  application:
    name: service-a
  cloud:
    nacos.discovery.server-addr: 49.234.134.34:8848
  profiles:
    active: server1

---
spring:
  profiles: server1
server:
  port: 8081
demo-test: service-a1
---
server:
  port: 8082
spring:
  profiles: server2
demo-test: service-a2
---

